// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your Firebase Web configuration
  // Run: flutterfire configure --platforms=web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_WEB_API_KEY',
    appId: 'YOUR_FIREBASE_WEB_APP_ID',
    messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
    projectId: 'YOUR_FIREBASE_PROJECT_ID',
    authDomain: 'YOUR_FIREBASE_AUTH_DOMAIN',
    storageBucket: 'YOUR_FIREBASE_STORAGE_BUCKET',
    measurementId: 'YOUR_FIREBASE_MEASUREMENT_ID',
  );

  // TODO: Replace with your Firebase Android configuration
  // Run: flutterfire configure --platforms=android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_ANDROID_API_KEY',
    appId: 'YOUR_FIREBASE_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
    projectId: 'YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'YOUR_FIREBASE_STORAGE_BUCKET',
  );

  // TODO: Replace with your Firebase iOS configuration
  // Run: flutterfire configure --platforms=ios
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_IOS_API_KEY',
    appId: 'YOUR_FIREBASE_IOS_APP_ID',
    messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
    projectId: 'YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'YOUR_FIREBASE_STORAGE_BUCKET',
    iosBundleId: 'com.example.trashpicker',
  );

  // TODO: Replace with your Firebase macOS configuration
  // Run: flutterfire configure --platforms=macos
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_MACOS_API_KEY',
    appId: 'YOUR_FIREBASE_MACOS_APP_ID',
    messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
    projectId: 'YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'YOUR_FIREBASE_STORAGE_BUCKET',
    iosBundleId: 'com.example.trashpicker',
  );

  // TODO: Replace with your Firebase Windows configuration
  // Run: flutterfire configure --platforms=windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_WINDOWS_API_KEY',
    appId: 'YOUR_FIREBASE_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
    projectId: 'YOUR_FIREBASE_PROJECT_ID',
    authDomain: 'YOUR_FIREBASE_AUTH_DOMAIN',
    storageBucket: 'YOUR_FIREBASE_STORAGE_BUCKET',
    measurementId: 'YOUR_FIREBASE_MEASUREMENT_ID',
  );
}
