// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKYpMPZGgdMTBbJtqXRQW52Zx5ZtbC54Q',
    appId: '1:453704785408:web:e658fe845b26cef6d902e5',
    messagingSenderId: '453704785408',
    projectId: 'trashpicker-2025',
    authDomain: 'trashpicker-2025.firebaseapp.com',
    storageBucket: 'trashpicker-2025.firebasestorage.app',
    measurementId: 'G-6ETH7G23H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRFf5ESygSUznYvqVprn1P5BwmsI2PIE',
    appId: '1:453704785408:android:7c7370822d5c6fa8d902e5',
    messagingSenderId: '453704785408',
    projectId: 'trashpicker-2025',
    storageBucket: 'trashpicker-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwB_3hRZCv2ivuj_KCfG49NRIcPF0q4Ys',
    appId: '1:453704785408:ios:e9238f72a88f8155d902e5',
    messagingSenderId: '453704785408',
    projectId: 'trashpicker-2025',
    storageBucket: 'trashpicker-2025.firebasestorage.app',
    iosBundleId: 'com.example.trashpicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwB_3hRZCv2ivuj_KCfG49NRIcPF0q4Ys',
    appId: '1:453704785408:ios:e9238f72a88f8155d902e5',
    messagingSenderId: '453704785408',
    projectId: 'trashpicker-2025',
    storageBucket: 'trashpicker-2025.firebasestorage.app',
    iosBundleId: 'com.example.trashpicker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKYpMPZGgdMTBbJtqXRQW52Zx5ZtbC54Q',
    appId: '1:453704785408:web:fc8cb51a39db2ec3d902e5',
    messagingSenderId: '453704785408',
    projectId: 'trashpicker-2025',
    authDomain: 'trashpicker-2025.firebaseapp.com',
    storageBucket: 'trashpicker-2025.firebasestorage.app',
    measurementId: 'G-FDLMFSKN5M',
  );
}
